### ISSUE TITLE
Add `src/temp` to `.gitignore`

### ISSUE THREAD

**Issue by rakr** [dxatscale/dxatscale-template#1] opened 2021-07-08 04:16 UTC

**Comment by ruslan-kurchenko** [comment] 2022-06-10 12:47
@rakr is by design `src/temp` should be in .gitignore to enforce developers to move files to relevant folders?

**Comment by rakr** [comment] 2022-06-11 01:31
@ruslan-kurchenko, this one has been open for conversation for quite some time.

For greenfield projects, my opinion is that we can keep the `src/temp` folder should as the default destination for new metadata pulled from Salesforce but still ignore it: "forcing" the developers to choose a proper location for that metadata. Part of the code review process would then be to review the final destination of the metadata.

For projects that are transitioning to a modular approach and are embracing Continuous Integration, I think that we have two options:

- **Option 1**: still ignore `src-temp`, this supports the approach where the transition is done alongside an "org based" approach where only the components that are in a module are considered.
- **Option 2**: do not ignore `src-temp`, this supports the approach where the first goal is to get all the metadata in a deployable state in a scratch org and the modularisation happens iteratively.

Now, how we ignore it is another story:

- at the version control level: probably yes, but I'm not convinced anymore that it should be done at the `.gitignore` level.
- at the CI/CD level, on one of our projects, here is how we are ignoring it and I think it's probably the right thing to do:

```
 {
  "path": "src-temp",
  "package": "src-temp",
  "versionNumber": "1.0.0.0",
  "default": true,
    "ignoreOnStage": [
    "prepare",
    "validate",
    "quickbuild",
    "build"
  ]
}
```

Thoughts

**Comment by rakr** [comment] 2022-06-11 01:33
I should probably close this issue as it has been resolved 😄

**Comment by azlam-abdulsalam** [comment] 2023-03-05 12:58
Closing this issue, as sfpowerscripts ignore package directories that do not have `package` attribute.   Developers could commit the src-temp folder to version control if required such as asking for advise on the location and also help between commits in a local worksation

**Closed by azlam-abdulsalam** 2023-03-05 12:58 UTC
